name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # daily at midnight
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate metrics.svg
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: introduction,achievements,recent_activity,coding_activity,languages_activity,projects

      - name: Commit and push metrics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add metrics.svg
          git commit -m "chore: update GitHub metrics" || echo "No changes to commit"
          git push
